### ISSUE TITLE
High level API wrapping most common actions with Channels

### ISSUE THREAD

**Issue by Meph1587** [iota-community/IOTAStreams#6]
In reference to issue #1 

### Rational
A high level API, or set of wrapper function, would drastically increase the usability and lower the barrier of entry of IOTA-Streams and more specifically IOTA Channels.
An additional level of abstraction would allow developers to more safely and quickly develop IOTA-Streams based use-cases. Without requiring deep knowledge of the underlying processes.

This is similar to the IOTA client API which has the option to use `send_transfers()` as  a single method instead of using `prepare_transfer()` + `GTTA()` + `attach_to_tangle()` + `broadcast_transaction()`

By giving both options, it is up to the developer to choose how much fine-tuning he is comfortable with.

###  Description
The API should have methods for the most common actions used in IOTA channels, these methods should also do most of the error handling to avoid confronting new developer with lower level errors.
for example:

**For the Author**
- opening a channel
- writing data to a channel
- removing a subscriber from a channel

**For the Subscriber**
- subscribe to a channel
- read from a channel 
- unsubscribes from channel

These methods could be bundled inside a `channel`.

### Examples
These are possible wrappings, which are not meant to be final by anyway, but should act more as a way to show how the complexity is decreased by condensing multiple steps :

`open_channel()`: creates the Author object, creates the announcement message and converts it to Trytes, generates the bundle and sends it to the node. It returns the message identifier.

`write_to_channel()`: converts a string or object to a public or masked payload, signs the payload and sends it.

`remove_subscribers()`: changes the author key, finds the subscribers that receive the new keys, published the new keys to those subscribers

`subscribe_to_channel()`: already good like its now, not much to condense 

`read_from_channel()`: receives message, parses header to packet, checks content type, unwraps packet an returns it

`unsubscribe_from_channel()`: already good like its now, not much to condense 

### References
[MAM Lite by stkubr](https://github.com/stkubr/MAML): A high level API for python MAM with only 4 methods: open, write, read and split_channel 

[Pay-per-data by AleBuser](https://github.com/AleBuser/IOTA-pay-per-data): A high level API for python to buy/sell data over MAML with 5 methods: open, send_package, check_payment, listen_for_packages, make_payment

**Comment by Meph1587** [comment]
Example of high level API implementation for Using IOTA-Streams with Tangle as transfer medium to enable Channel Application.

This code is based on the channels-example repo by @JakeSCahill
[https://github.com/AleBuser/channels-examples](https://github.com/AleBuser/channels-examples)

The goal was to remove as much configuration details as possible from the API, making it very easy to create and write to a channel.
**Progress:**
- [x] open channel
- [x]  write to channel 
- [ ]  remove subscriber from channel
- [x] subscribe to channel (bundle bug to be fixed first)
- [x] read from channel (bundle bug to be fixed first)

**Comment by Meph1587** [comment]
First version of the implementation with full functionality, ready for feedback:
https://github.com/AleBuser/iota-channels-lite
(channel_author.change_key is missing)
